### ISSUE TITLE
edX specific string 

### ISSUE THREAD

**Issue by sambapete** [openedx/frontend-app-profile#686]
In [frontend-app-profile](https://github.com/openedx/frontend-app-profile)/[src](https://github.com/openedx/frontend-app-profile/tree/master/src)/[skills-builder](https://github.com/openedx/frontend-app-profile/tree/master/src/skills-builder)/[skills-builder-header](https://github.com/openedx/frontend-app-profile/tree/master/src/skills-builder/skills-builder-header)/messages.js

"Let edX be your guide"

It should use the name of the platform currently being used and not be edX specific.

Thank you.

**Comment by kdmccormick** [comment]
Done here: https://github.com/openedx/frontend-app-profile/pull/791
